version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # internal Kafka listener
      - "29092:29092" # external access from host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  service1:
    build:
      context: .
      dockerfile: SampleService1/Dockerfile
    depends_on:
      - kafka
    environment:
      Kafka__BootstrapServers: kafka:9092

  service2:
    build:
      context: .
      dockerfile: SampleService2/Dockerfile
    depends_on:
      - kafka
    environment:
      Kafka__BootstrapServers: kafka:9092

  logservice:
    build:
      context: .
      dockerfile: LogService/Dockerfile
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - ./logs:/app/logs
    environment:
      Kafka__BootstrapServers: kafka:9092
      Elasticsearch__Uri: http://elasticsearch:9200
      Elasticsearch__Index: logs-index